export const dataList = [
  {
    id: 1,
    name: "证件",
    children: [
      { id: 1, name: "身份证", normal: true },
      { id: 2, name: "驾照", normal: true },
      { id: 3, name: "split" },
      { id: 4, name: "护照" },
    ],
  },
  {
    id: 2,
    name: "日用品",
    children: [
      { id: 1, name: "牙刷", normal: true },
      { id: 2, name: "毛巾", normal: true },
      { id: 3, name: "纸巾/湿巾", normal: true },
      { id: 4, name: "一次性厕所垫" },
      { id: 5, name: "一次性床垫" },
      { id: 6, name: "一次性毛巾" },
      { id: 7, name: "水杯" },
      { id: 7, name: "洗澡夹头发夹" },
      { id: 8, name: "split" },
      { id: 9, name: "m巾" },
      { id: 10, name: "驱蚊水" },
      { id: 11, name: "浴帽" },
    ],
  },
  {
    id: 3,
    name: "电器",
    children: [
      { id: 10, name: "充电线（typec， usb）", normal: true },
      { id: 11, name: "充电宝（满电可用）", normal: true },
      { id: 12, name: "相机" },
      { id: 13, name: "分线器" },
    ],
  },
  {
    id: 4,
    name: "衣服",
    children: [
      { id: 13, name: "遮阳帽" },
      { id: 14, name: "鞋套" },
      { id: 15, name: "雨衣" },
      { id: 16, name: "迪卡侬口袋外套" },
    ],
  },
  {
    id: 5,
    name: "药物",
    children: [
      { id: 13, name: "吗丁啉" },
      { id: 14, name: "消食片" },
      { id: 15, name: "保济丸" },
      { id: 16, name: "布洛芬" },
      { id: 17, name: "创可贴" },
      { id: 18, name: "消毒药水棉签" },
      { id: 19, name: "金莲花" },
    ],
  },
  {
    id: 6,
    name: "其他",
    children: [
      { id: 13, name: "现金" },
      { id: 14, name: "口罩" },
      { id: 15, name: "酒精" },
      { id: 16, name: "拖鞋" },
      { id: 17, name: "笔" },
      { id: 18, name: "备用袋子（装杂碎，衣服）" },
      { id: 19, name: "垃圾袋" },
      { id: 20, name: "门锁扣" },
      { id: 21, name: "耳塞" },
      { id: 22, name: "偏振镜" },
      { id: 23, name: "除渍笔" },
      { id: 24, name: "红外检测仪+美纹纸" },
      {
        id: 25,
        name: "游水相关",
        children: [
          { id: 13, name: "泳衣" },
          { id: 14, name: "泳镜" },
          { id: 15, name: "泳帽" },
          { id: 16, name: "手机防水袋" },
        ],
      },
    ],
  },
];
